#' @importFrom utils globalVariables
#' 
utils::globalVariables(c("chr", "pos", "cpg_n", "quantile", "start", 
                        "value", "variable", "status", 
                        "sd_2_lower", "sd_2_upper", "sd_1.5_lower",
                        "sd_1.5_upper", "sd_1_lower", "sd_1_upper",
                        "betas", "type", "txdb", "mapIds", "UcscTrack",
                        "browserSession", "getTable", "genome<-",
                        "ucscTableQuery", "DataTrack", "AnnotationHub",
                        "query", "useEnsembl", "useDataset", "getBM",
                        "melt", "seqlevelsStyle<-", "bplapply", 
                        "ExperimentHub", "geom_text_repel", "IdeogramTrack",
                        "GenomeAxisTrack", "GeneRegionTrack", 
                        "HighlightTrack", "grid.grabExpr", "dev.new", 
                        "plotTracks", "grid.arrange",
                        "TxDb.Hsapiens.UCSC.hg19.knownGene", 
                        "TxDb.Hsapiens.UCSC.hg38.knownGene", 
                        "TxDb.Hsapiens.UCSC.hg18.knownGene", "seqnames",
                        "Homo.sapiens", "as_tibble", "pmap_dbl",
                        "getM", "residuals", "ilogit2", "featureNames"))